### PR TITLE
Challenge 2 resubmit and Challenge 3 

### PR DESCRIPTION
**Pull request by quinn556**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I see a duplicate for week 2 challenge. Please remove one of them
Secondly, please remove space from Week2_challenge_Quinn He (make it like Quinn_He). 
Thirdly I see freeze files for week 3 but no week 3 files in posts. You dont want to submit me yet?

Schedule an appointment in case of issues.

**Comment by quinn556** [comment]
I believe I just deleted one of the Challenge 2 submissions. For your third point, I thought you wanted me to submit just the freeze files? I can try submitting the to the posts for the Week 3 challenge if you still need those files.

**Review by SidharthSaluja — COMMENTED** [review]
I need the challenge 3 in posts folder even though I received ur freeze files for challenge3. 
Secondly please remove space from name of _posts/Week2_Challenge_Quinn He. It should be posts/Week2_Challenge_Quinn_He.qmd. Render and send me again

**Comment by quinn556** [comment]
I think I renamed challenge 2. I rendered it and did not see the”_posts” that you are referring to so I hope what I did worked. My week 3 challenge is also in the posts folder on my end so I tried to fix that through a submission.

**Review by SidharthSaluja — COMMENTED** [review]
Let me be more clear -
1) In the posts folder, I see QH_Week2_Challenge.qmd. Remove that (since there is two week 2 files submitted)
2) In posts folder, I still see a space between file name of Week2_Challenge_Quinn He. It should be Week2_Challenge_Quinn_He (in Quinn He there is a space make it Quinn_He). Render this and commit again. 


Schedule an appointment if it still doesnt clear up. Happy to help

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
