### PR TITLE
Week 1 and week 2 challenge by Erika Nagai

### PR DESCRIPTION
**Pull request by Enagai-nagai**
Thanks for the comment.
I added freeze files (rendered files) and also added a week1 tutorial file. I had mistakenly deleted it so I uploaded it again.
I hope it work.

I closed the previous pull request to send the new one.

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I see some changes in the _templates folder. Did you change something in that? Also did you sync the fork

**Comment by Enagai-nagai** [comment]
Hi Sidharth,

Yes, as I wrote in the comment, I deleted the week 1 tutorial file in the
template folder because I was overwriting my code there instead of making
my own file in the pot folder.
Thus, I uploaded the week 1 tutorial file exactly the same as the original
one (copied the code in the DACSS network repo) in my repository.
My repository is synced with the DACSS repo as the following picture shows.
[image: image.png]

Please let me know what I can do so you accept the pull request.

Best regards,
Erika


2023年2月28日(火) 18:21 Sidharth Saluja ***@***.***>:

**Comment by Enagai-nagai** [comment]
Can you accept the pull request or let me know what I can do so you accept it?

**Review by SidharthSaluja — COMMENTED** [review]
I am seeing merge conflicts because of the _templates file being modified. Could you slack me or schedule a meeting on me. I need to go through what is exactly going wrong.

**Comment by SidharthSaluja** [comment]
What I feel like since there already existed file. But the file was deleted and we added same contents. It will show same merge conflicts. Do you have GitHub desktop, if not please install that. it would help to overcome this error. We just have to revert the changes of this file.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
