### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kdocekal**
Final Project, Wk7 and Wk9 challenges.

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Just render your qmd files to generate _freeze folder. So, I need that freeze folder too

**Comment by kdocekal** [comment]
Renders complete, the freeze folder should be there. Thanks.

**Review by SidharthSaluja — COMMENTED** [review]
Just remove site_libs folder from _freeze rest is all set

**Comment by kdocekal** [comment]
site_libs folder removed.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
