### PR TITLE
Challenge 1 Alex Genovese

### PR DESCRIPTION
**Pull request by AGenovese-1**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
If you want to send week 1 challenge instructions to students. They upload their challenges or solutions to _templates folder in template branch (For that I they can ask me to upload too or they can do manually). Additionally to show challenges/solutions on webpage they upload it to submission branch of the posts folder. They send me pull request and I approve that.

Please slack me if still in doubt we can have meeting tomorrow.

**Comment by SidharthSaluja** [comment]
Also I see exact same challenge instructions in the _templates folder. It is already displayed to students on the blog too. Just the author name is different

**Review by SidharthSaluja — COMMENTED** [review]
I think it is solution instead of instructions

**Comment by mrolfe** [comment]
@AGenovese-1 you need to submit to submission (not template) and be sure to rename your file and retitle it so that it is clear that it is your post (not just the original instructions.)

**Comment by AGenovese-1** [comment]
@SidharthSaluja Should be all set now. Sorry!

**Review by SidharthSaluja — COMMENTED** [review]
The solutions should go in the submission branch (not template branch). Could you also render the file to include freeze files too. Sorry, but this is required for fast rendering

**Review by SidharthSaluja — COMMENTED** [review]
Yup everything looks fine just change the branch to submission instead of template.

**Review by SidharthSaluja — COMMENTED** [review]
Ok looks like as a new pull request, I received correct things. I am closing this pull request since I merged the latest one.

**Pull request closed without merging**
