### PR TITLE
Submitting final project

### PR DESCRIPTION
**Pull request by mekh09**
I tried to remove unwanted files, I am not sure if they are in the way.

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Please remove all space from folders and filenames. It is a good practice that file name shouldn’t have space between them so for example posts/_data/Mekhala's data should be  posts/_data/Mekhala_data. 

2. Rename your Migration Network.qmd  file to Migration_Networks_{Yourname}.qmd
3. I think you forgot to submit me challenge 4 qmd file in the post folder. Note that you should include your name in the file like challenge4_{Yourname}.qmd

4. Your _freeze is messed up. So please delete _freeze folder and re-render all files you are submitting me in the post folder to generate new freeze files.

**Comment by mekh09** [comment]
I will make the changes. I did not want to submit challenge 4 but I think for some reason the file was present there

**Comment by mekh09** [comment]
I have made the changes. Please let me know if there is anything else that is required.

**Review by SidharthSaluja — COMMENTED** [review]
Delete Mekhla’s data folder and Migration Networks.qmd. Rest is fine.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
