### PR TITLE
WK1 Challenge

### PR DESCRIPTION
**Pull request by kdocekal**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Went you suppose to submit .qmd in the posts folder. I see it outside post folder. Also shouldn’t it be a qmd file? Also please include freeze files. Render your qmd file to get freeze files

**Comment by kdocekal** [comment]
Thanks for the comments, sorry I uploaded the wrong file. The correct qmd file should be in the post folder now.

**Review by SidharthSaluja — COMMENTED** [review]
Everything looks fine. But I forgot to mention one thing earlier which I just noticed. Could you rename wk1Challenge.qmd to something like Week1Challenge_{Yourfullname}.qmd. It is important to include your name to avoid merge issues.

**Comment by kdocekal** [comment]
Thanks for letting me know, the file should be updated now.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
