### PR TITLE
Social Networks_Final Project

### PR DESCRIPTION
**Pull request by nihapola**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
1. Rename your Homework1.qmd to Homework1_{Yourname}.qmd to avoid merge conflicts
2. Rename posts/SN_Final Project.qmd similarly as above and make sure you dont have space between file names
3. Rename week1_challenge.qmd to week1_challenge_{Yourname}.qmd and do same for every week change.
4. Your csv file should be in separate folder like posts/DataFolder_{Yourname}
5. Delete your freeze folder bcs it will contain bad file names
6. After renaming every file accordingly render your files to generate _freeze folder again.

Send me .qmds in post folder, _freeze folder, and your data folder(datafolder is optional)

**Comment by nihapola** [comment]
The above mentioned changes have been made. Please let me know if anything else is missing. Thank you.

**Comment by nihapola** [comment]
The changes have been made

**Review by SidharthSaluja — COMMENTED** [review]
You are awsome

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
