### PR TITLE
Final Project Submission by Erika Nagai

### PR DESCRIPTION
**Pull request by Enagai-nagai**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Rename Kpop_network.qmd to Kprop_network_ErikaNagai.qmd and render it again and send me freeze

**Comment by Enagai-nagai** [comment]
Hi I added frozen files! I hope it works now. 
Thank you!

**Comment by SidharthSaluja** [comment]
Nope the file I said to rename is not yet renamed. Read my above comment again

**Comment by Enagai-nagai** [comment]
Sorry about that.
I actually deleted "Kpop_network.qmd" as it was no longer necessary, "Final_Project_Kpop_network_Erika_Nagai.qmd" is the new version.

**Review by SidharthSaluja — APPROVED** [review]
Perfect

**Pull request merged**
