### PR TITLE
Challenge 3

### PR DESCRIPTION
**Pull request by kamuhammad**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Some modifications -
1. Rename Week1_Challenge.qmd to Week1_Challenge_kmuhammad.qmd

Please render your .qmd files to generate freeze files and send me that

**Comment by kamuhammad** [comment]
I renamed the file and added it to my posts folder, but it appears I cannot attach the files here. Should I email the files or upload another way?

Thank you.

**Review by SidharthSaluja — COMMENTED** [review]
I didnt understand what you mean by can’t you attach/commit files. 

More suggestions - 
1. Delete Week1_challenge.qmd (because I said to rename that file but looks like you added a file with correct name so I dont need this file now. The correct named file is good)
2. All you have to do is go to the .qmd file and hit render. This will generate _freeze files. Commit those files too. It will show in the git tab

**Review by SidharthSaluja — COMMENTED** [review]
I didnt understand what you mean by can’t you attach/commit files. 

More suggestions - 
1. Delete Week1_challenge.qmd (because I said to rename that file but looks like you added a file with correct name so I dont need this file now. The correct named file is good)
2. All you have to do is go to the .qmd file and hit render. This will generate _freeze files. Commit those files too. It will show in the git tab

**Comment by kamuhammad** [comment]
Hi, 

Can you check that this file is ready to post again? I have a number of other submissions in the queue.

Thank you.

**Review by SidharthSaluja — COMMENTED** [review]
I didnt receive the freeze files. Render your qmd file to generate freeze files.

**Comment by kamuhammad** [comment]
Hi,

I deleted the original files, re-rendered them, and created a new pull
request. Please let me know if anything else is needed.

Thank you,
Kalimah

**Pull request closed without merging**
